stages:
  - test
  - deploy

sast:
  stage: test

deploy:
  image: node:gallium
  only:
    - tags
  stage: deploy
  before_script:
    - yarn
  script:
    - yarn npm publish

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
