name: Publish Package

on:
  release:
    types: [created]

permissions:
  id-token: write
  contents: write

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
      - run: npm --no-git-tag-version version from-git
      - run: npm publish
